version: '3.7'

services:
  habit-tracker-db:
    image: 'postgres:11.3-alpine'
    container_name: habit_tracker_pg
    restart: 'always'

    ports:
      - "${PG_PORT}:${PG_PORT}"

    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD

    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
