version: '3.5'

services:
  db:
    image: 'postgres:11.3-alpine'
    restart: 'always'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'habit_tracker'
      POSTGRES_PASSWORD: 'CWT7Dk2ayp8u'

  habit-tracker:
    build: .
    command: yarn start:debug
    volumes:
      - './src:/home/node/app/src'
    env_file: .env
    environment:
     - SNYK_TOKEN=${SNYK_TOKEN}
    depends_on:
      - db
