version: '3.7'

services:
  habit-tracker-db:
    image: 'postgres:11.3-alpine'
    container_name: habit_tracker_pg
    restart: 'always'

    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD

    volumes:
      - pgdata:/var/lib/postgresql/data

    networks:
      - habit-tracker-network

  habit-tracker:
    depends_on:
      - habit-tracker-db

    ports:
      - "${PORT}:${PORT}"

    build: .
    container_name: habit_tracker
    restart: unless-stopped

    environment:
      - PORT
      - TYPEORM_CONNECTION
      - TYPEORM_HOST
      - TYPEORM_USERNAME
      - TYPEORM_PASSWORD
      - TYPEORM_DATABASE
      - TYPEORM_PORT
      - TYPEORM_SYNCHRONIZE
      - TYPEORM_LOGGING
      - TYPEORM_ENTITIES
      - AUTH_JWT_SECRET
      - AUTH_SALT_ROUNDS

    command: node dist/main.js

    volumes:
      - './:/home/node/app'
      - node_modules:/home/node/app/node_modules

    networks:
      - habit-tracker-network

networks:
  habit-tracker-network:
    driver: bridge

volumes:
  pgdata:
  node_modules:
