version: '3.7'

services:
  db:
    image: 'postgres:11.3-alpine'
    restart: 'always'

    ports:
      - "${PG_PORT}:${PG_PORT}"

    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD

    volumes:
      - pgdata:/var/lib/postgresql/data


  message-broker:
    image: 'rabbitmq:3.7-alpine'

volumes:
  pgdata:
